### ISSUE TITLE
Use TLS from the router by setting argo to edge

### ISSUE THREAD

**Issue by gnunn1** [OpenShiftDemos/openshift-gitops-workshop#12]
Update the argocd CR to use edge instead of passthrough so we can leverage the valid router certificate.

```
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
```
